### ISSUE TITLE
Comparison with postcss-extend

### ISSUE THREAD

**Issue by timkelty** [GarthDB/postcss-inherit#154]
Wondering if a spot in the readme could acknowledge the differences between this project and https://github.com/travco/postcss-extend.

**Comment by GarthDB** [comment]
Would you like to make a pull request?

**Comment by timkelty** [comment]
Sure.
I'd also be curious to hear your thoughts, and if you intentionally made this as an alternative to `postcss-extend`.

**Comment by GarthDB** [comment]
It was primarily created to transition a project from rework which had a plugin with similar functionality.

**Comment by timkelty** [comment]
Gotcha. I'll play around with it and see if I can make PR to the readme.
